### PR TITLE
Add dark mode for the website

### PR DESCRIPTION
**Pull request by ArunBohra12**
- Made spinner transparent
- Did changes in CSS & JS for dark mode
- Remove unnecessary imports in CSS

### CODE REVIEW

**Comment by KiranAminPanjwani** [comment]
> * Made spinner transparent
> * Did changes in CSS & JS for dark mode
> * Remove unnecessary imports in CSS

Please mention the issue number and provide screenshots of the changes you have made. For example, a screenshot for dark mode/transparent spinner.

**Comment by ArunBohra12** [comment]
Issue: #29 

Preview for dark mode
- **Dark Mode**
  
- **Transparent Spinner** (it used to have a white background around the spinner) 
  

Additionally, we can see more of it in the netlify [deploy preview](https://deploy-preview-44--leatherhoard.netlify.app/)

**Review by KiranAminPanjwani — APPROVED** [review]
Awesome! ✨

**Comment by KiranAminPanjwani** [comment]
@ArunBohra12 There are 7 conflicts in the file. These conflicts are shown due to these comments:
image

To resolve conflicts, please add your comments like this:   /* [ your comments ] */

**Comment by KiranAminPanjwani** [comment]
Happy Contributing! 😊🎉

**Pull request merged**
