### PR TITLE
loader fixes

### PR DESCRIPTION
**Pull request by kunaaal13**
Loader animation is fixed and also the time of the loader is increased to 2.5 seconds

### CODE REVIEW

**Review by KiranAminPanjwani — COMMENTED** [review]
The preloader is looking very good. But can you please match its color with the overall theme color of the website? For example Brown or light pink?

**Comment by kunaaal13** [comment]
Yeah sure I'll fix that

**Comment by KiranAminPanjwani** [comment]
Also, please mention the issue number.

**Comment by kunaaal13** [comment]
@KiranAminPanjwani this is fixed now issue no 39

**Comment by KiranAminPanjwani** [comment]
Happy Contributing! 😊🎉

**Pull request merged**
