### PR TITLE
Made cursor pointer and added link of product to product section

### PR DESCRIPTION
**Pull request by AnshuPathak-88825**

### CODE REVIEW

**Comment by AnshuPathak-88825** [comment]
Also made transition smooth while hover 
Pr for #66

**Comment by KiranAminPanjwani** [comment]
You have raised the issue for the cursor pointer only. 

image

Please don't add the link of "product.html". Because I want a separate description page for each product so that users can buy the product.

**Comment by AnshuPathak-88825** [comment]
Do you want me to remove smooth transition too ? @KiranAminPanjwani

**Comment by KiranAminPanjwani** [comment]
> Do you want me to remove smooth transition too ? @KiranAminPanjwani

No that is fine. ✨

**Comment by AnshuPathak-88825** [comment]
pls merge it

**Comment by AnshuPathak-88825** [comment]
I made all changes

**Pull request merged**
