### PR TITLE
Added offer section

### LINKED ISSUE #28: Adding new offer section & some extra features
Adding new offer section for exclusive products.
Some extra features & effect with css to some sections of  webpage.
Please assign me!

### LINKED ISSUE #31: Make contact input fields more intuitive
When we focus on any of the input fields from the `Contact us` form, that field doesn't reflect the user's action. I think we should show box shadow around the input field, something like the below image - 
focus-effect

Can I please include this in this project?

### PR DESCRIPTION
**Pull request by Ankit-11525**
## 🛠️ Fixes Issue
I have added the offer section in the main page 
Closes #28 

## 👨‍💻 Changes proposed
This website is looking good but with offer section it looks great ,i have added OFFER SECTION, which very fascinating for customers.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I am a participant of Hacktoberfest 2022.

## 📄 Note to reviewers
Please add lebels like "hacktoberfest"  "hacktoberfest-accepted" "hacktoberfest-updated"

## 📷 Screenshots
offer section Screenshot

### CODE REVIEW

**Comment by Ankit-11525** [comment]
I have added offer section please merge it to your main page
PR  issue #28

**Comment by Ankit-11525** [comment]
I have updated the above condition and informations,Please merge it to your main branch

**Review by KiranAminPanjwani — APPROVED** [review]
Awesome!✨
Happy Contributing! 😊🎉

**Comment by KiranAminPanjwani** [comment]
@Ankit-11525 Please create a new PR and try to fix the offer section. I think something has gone wrong.
Please visit: https://leatherhoard.netlify.app/

**Comment by Ankit-11525** [comment]
Okay wait i will find what's the problem.

**Pull request merged**
