### PR TITLE
feat: product page created 

### PR DESCRIPTION
**Pull request by amitanshusahu**
### Created a product page 
have a look 👇🏻  

image

## video example  👇🏻 
[screen-recorder-sat-oct-01-2022-16-56-37.webm](https://user-images.githubusercontent.com/83657737/193407407-55fc79b3-ea7d-4092-b238-b7af0ec0b7cd.webm)

### CODE REVIEW

**Review by KiranAminPanjwani — APPROVED** [review]
That's Awesome! ✨ Please mention your issue number in the comment.
Happy Contributing! 😊🎉

**Comment by amitanshusahu** [comment]
Thanks 🤩  , it was my 1st PR ..
### issue no - 21

@KiranAminPanjwani

**Comment by KiranAminPanjwani** [comment]
> Thanks 🤩 , it was my 1st PR ..
> 
> ### issue no - 21
> @KiranAminPanjwani

Please link your Products.html file with the index.html. 
You can replace "blog.html" in the "View More" button:

image

**Comment by amitanshusahu** [comment]
> > Thanks star_struck , it was my 1st PR ..
> > ### issue no - 21
> > @KiranAminPanjwani
> 
> Please link your Products.html file with the index.html. You can replace "blog.html" in the "View More" button:
> 
> image

# Ok 😊

**Pull request merged**
