### PR TITLE
add hover effect to card-service class

### PR DESCRIPTION
**Pull request by Hasib24**
Screenshot_5

I have added card hover effect.

### CODE REVIEW

**Comment by KiranAminPanjwani** [comment]
Please add a hover effect to cards for light mode as well. 😊

**Comment by KiranAminPanjwani** [comment]
@Hasib24 Done?

**Review by KiranAminPanjwani — APPROVED** [review]
Thankyou. ✨
Happy Contributing! 😊🎉

**Comment by Hasib24** [comment]
> @Hasib24 Done?

i am sorry to say that color variable is not working. I don't know why

**Pull request merged**
