### PR TITLE
Active login menu item in login page

### LINKED ISSUE #70: [Bug] Wrong menu selected in login page
### Description

Instead of the login menu selected, we can see 'Home' menu is active/selected on the login page. Can I please work on this?

### Screenshots

image

### PR DESCRIPTION
**Pull request by rezwan2525**
## 🛠️ Fixes Issue : ""
This PR closes #70 and #68 both

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I am a participant of Hacktoberfest 2022.

## 📄 Note to reviewers
This PR solves both issues because after linking to `theme.js` file from `login page`, we are getting the correct theme behavior in the login page, which was missing before.
1. `Login` menu item will be active on the login page. 
2. Hovering on social icons is same as the home page

## 📷 Screenshots
**Current menu in login page**
image

**Current footer social icons**
image

### CODE REVIEW

**Comment by KiranAminPanjwani** [comment]
You should create a separate PR for each specific issue. Otherwise, there is no point in making 2 issues.

**Comment by rezwan2525** [comment]
@KiranAminPanjwani Actually, code changes of #70, automatically resolves issue #68. So, we don't need any more code changes for #68. That's why I've created one PR for those two issues. I hope you will understand.

**Comment by KiranAminPanjwani** [comment]
> @KiranAminPanjwani Actually, code changes of #70, automatically resolves issue #68. So, we don't need any more code changes for #68. That's why I've created one PR for those two issues. Also, while I was creating issues, I didn't know how those issues are going to be resolved. That's why we had created two different issues then. I hope you will understand.

Okay, no worries.😊

**Review by KiranAminPanjwani — APPROVED** [review]
Happy Contributing! 😊🎉

**Pull request merged**
