### PR TITLE
added a refund policy section

### LINKED ISSUE #22: I would like to add a cancellation/refund policy for your product page

Kindly assign me the same under hackotober fest 2022
@KiranAminPanjwani

### PR DESCRIPTION
**Pull request by Janhvi52**
Closes #22 

🛠️ Fixes Issue #22 

## 👨‍💻 Changes proposed: 
The task was to add a refund/cancellation policy section to the website

## ✔️ Check List (Check all the applicable boxes) 
- [✔️ ] My code follows the code style of this project.
- [ ✔️] This PR does not contain plagiarized content.
- [✔️ ] The title of my pull request is a short description of the requested changes.
- [✔️ ] I am a participant of Hacktoberfest 2022.

## 📄 Note to reviewers
I've added a refund/cancellation policy section to the home page of your website

## 📷 Screenshots

Screenshot (55)

The refund/cancellation policy section looks like this!

Hope you like it @KiranAminPanjwani

### CODE REVIEW

**Comment by KiranAminPanjwani** [comment]
Dear, your work is nice.✨ But it is not according to the overall theme of the website. Also, the Nav link is not working.
kindly change it, if possible. 😊

**Comment by Janhvi52** [comment]
> Dear, your work is nice.✨ But it is not according to the overall theme of the website. Also, the Nav link is not working. kindly change it, if possible. 😊

heyy
i've changed the background color as per your website requirements and also fixed the nav link
hope you likt it! @KiranAminPanjwani 
Screenshot (58)

Screenshot (59)

**Comment by KiranAminPanjwani** [comment]
Please change the image. Try to use brown-white images.

**Comment by Janhvi52** [comment]
> Please change the image. Try to use brown-white images.

okay I'll change it :) 
@KiranAminPanjwani 
rest all things were okay right?

**Comment by Janhvi52** [comment]
Screenshot (61)

hope it will work @KiranAminPanjwani

**Comment by Janhvi52** [comment]
heyy, any problem with this section @KiranAminPanjwani

**Comment by KiranAminPanjwani** [comment]
> heyy, any problem with this section @KiranAminPanjwani 

Your changes are not according to the requirements.

**Pull request closed without merging**
